package versions

// Data component type ids for Minecraft 1.21.4.
//
// Code generated by internal/gen/gencomponents.mjs from the server's own
// registries report. DO NOT EDIT.
//
// Keys are this version's wire ids; values are the canonical ids that
// understudy/components.go switches on, which is 26.1's numbering. An id absent
// from this map is a component this decoder has no shape for.
var v1_21_4ComponentIDs = map[int32]int32{
	0:  0,  // custom_data
	1:  1,  // max_stack_size
	2:  2,  // max_damage
	3:  3,  // damage
	4:  4,  // unbreakable
	5:  6,  // custom_name
	6:  9,  // item_name
	7:  10, // item_model
	8:  11, // lore
	9:  12, // rarity
	10: 13, // enchantments
	11: 14, // can_place_on
	12: 15, // can_break
	13: 16, // attribute_modifiers
	14: 17, // custom_model_data
	17: 19, // repair_cost
	18: 20, // creative_slot_lock
	19: 21, // enchantment_glint_override
	20: 22, // intangible_projectile
	21: 23, // food
	22: 24, // consumable
	23: 25, // use_remainder
	24: 26, // use_cooldown
	25: 27, // damage_resistant
	26: 28, // tool
	27: 31, // enchantable
	28: 32, // equippable
	29: 33, // repairable
	30: 34, // glider
	31: 35, // tooltip_style
	32: 36, // death_protection
	33: 42, // stored_enchantments
	34: 44, // dyed_color
	35: 45, // map_color
	36: 46, // map_id
	37: 47, // map_decorations
	38: 48, // map_post_processing
	39: 49, // charged_projectiles
	40: 50, // bundle_contents
	41: 51, // potion_contents
	42: 53, // suspicious_stew_effects
	43: 54, // writable_book_content
	44: 55, // written_book_content
	45: 56, // trim
	46: 57, // debug_stick_state
	47: 58, // entity_data
	48: 59, // bucket_entity_data
	49: 60, // block_entity_data
	50: 61, // instrument
	51: 63, // ominous_bottle_amplifier
	52: 64, // jukebox_playable
	53: 66, // recipes
	54: 67, // lodestone_tracker
	55: 68, // firework_explosion
	56: 69, // fireworks
	57: 70, // profile
	58: 71, // note_block_sound
	59: 72, // banner_patterns
	60: 73, // base_color
	61: 74, // pot_decorations
	62: 75, // container
	63: 76, // block_state
	64: 77, // bees
	65: 78, // lock
	66: 79, // container_loot
}

// Slot display kinds for Minecraft 1.21.4, mapped to canonical ids the same
// way and for the same reason: they are registry indices and they move.
var v1_21_4SlotDisplayIDs = map[int32]int32{
	0: 0,  // empty
	1: 1,  // any_fuel
	2: 4,  // item
	3: 5,  // item_stack
	4: 6,  // tag
	5: 8,  // smithing_trim
	6: 9,  // with_remainder
	7: 10, // composite
}
