package versions

// Data component type ids for Minecraft 1.21.11.
//
// Code generated by internal/gen/gencomponents.mjs from the server's own
// registries report. DO NOT EDIT.
//
// Keys are this version's wire ids; values are the canonical ids that
// understudy/components.go switches on, which is 26.1's numbering. An id absent
// from this map is a component this decoder has no shape for.
var v1_21_11ComponentIDs = map[int32]int32{
	0:   0,   // custom_data
	1:   1,   // max_stack_size
	2:   2,   // max_damage
	3:   3,   // damage
	4:   4,   // unbreakable
	5:   5,   // use_effects
	6:   6,   // custom_name
	7:   7,   // minimum_attack_charge
	8:   8,   // damage_type
	9:   9,   // item_name
	10:  10,  // item_model
	11:  11,  // lore
	12:  12,  // rarity
	13:  13,  // enchantments
	14:  14,  // can_place_on
	15:  15,  // can_break
	16:  16,  // attribute_modifiers
	17:  17,  // custom_model_data
	18:  18,  // tooltip_display
	19:  19,  // repair_cost
	20:  20,  // creative_slot_lock
	21:  21,  // enchantment_glint_override
	22:  22,  // intangible_projectile
	23:  23,  // food
	24:  24,  // consumable
	25:  25,  // use_remainder
	26:  26,  // use_cooldown
	27:  27,  // damage_resistant
	28:  28,  // tool
	29:  29,  // weapon
	30:  30,  // attack_range
	31:  31,  // enchantable
	32:  32,  // equippable
	33:  33,  // repairable
	34:  34,  // glider
	35:  35,  // tooltip_style
	36:  36,  // death_protection
	37:  37,  // blocks_attacks
	38:  38,  // piercing_weapon
	39:  39,  // kinetic_weapon
	40:  40,  // swing_animation
	41:  42,  // stored_enchantments
	42:  44,  // dyed_color
	43:  45,  // map_color
	44:  46,  // map_id
	45:  47,  // map_decorations
	46:  48,  // map_post_processing
	47:  49,  // charged_projectiles
	48:  50,  // bundle_contents
	49:  51,  // potion_contents
	50:  52,  // potion_duration_scale
	51:  53,  // suspicious_stew_effects
	52:  54,  // writable_book_content
	53:  55,  // written_book_content
	54:  56,  // trim
	55:  57,  // debug_stick_state
	56:  58,  // entity_data
	57:  59,  // bucket_entity_data
	58:  60,  // block_entity_data
	59:  61,  // instrument
	60:  62,  // provides_trim_material
	61:  63,  // ominous_bottle_amplifier
	62:  64,  // jukebox_playable
	63:  65,  // provides_banner_patterns
	64:  66,  // recipes
	65:  67,  // lodestone_tracker
	66:  68,  // firework_explosion
	67:  69,  // fireworks
	68:  70,  // profile
	69:  71,  // note_block_sound
	70:  72,  // banner_patterns
	71:  73,  // base_color
	72:  74,  // pot_decorations
	73:  75,  // container
	74:  76,  // block_state
	75:  77,  // bees
	76:  78,  // lock
	77:  79,  // container_loot
	78:  80,  // break_sound
	79:  81,  // villager/variant
	80:  82,  // wolf/variant
	81:  83,  // wolf/sound_variant
	82:  84,  // wolf/collar
	83:  85,  // fox/variant
	84:  86,  // salmon/size
	85:  87,  // parrot/variant
	86:  88,  // tropical_fish/pattern
	87:  89,  // tropical_fish/base_color
	88:  90,  // tropical_fish/pattern_color
	89:  91,  // mooshroom/variant
	90:  92,  // rabbit/variant
	91:  93,  // pig/variant
	92:  95,  // cow/variant
	93:  97,  // chicken/variant
	94:  99,  // zombie_nautilus/variant
	95:  100, // frog/variant
	96:  101, // horse/variant
	97:  102, // painting/variant
	98:  103, // llama/variant
	99:  104, // axolotl/variant
	100: 105, // cat/variant
	101: 107, // cat/collar
	102: 108, // sheep/color
	103: 109, // shulker/color
}

// Slot display kinds for Minecraft 1.21.11, mapped to canonical ids the same
// way and for the same reason: they are registry indices and they move.
var v1_21_11SlotDisplayIDs = map[int32]int32{
	0: 0,  // empty
	1: 1,  // any_fuel
	2: 4,  // item
	3: 5,  // item_stack
	4: 6,  // tag
	5: 8,  // smithing_trim
	6: 9,  // with_remainder
	7: 10, // composite
}
