package versions

// Data component type ids for Minecraft 26.2.
//
// Code generated by internal/gen/gencomponents.mjs from the server's own
// registries report. DO NOT EDIT.
//
// Keys are this version's wire ids; values are the canonical ids that
// understudy/components.go switches on, which is 26.1's numbering. An id absent
// from this map is a component this decoder has no shape for.
var v26_2ComponentIDs = map[int32]int32{
	0:   0,   // custom_data
	1:   1,   // max_stack_size
	2:   2,   // max_damage
	3:   3,   // damage
	4:   4,   // unbreakable
	5:   5,   // use_effects
	6:   6,   // custom_name
	7:   7,   // minimum_attack_charge
	8:   8,   // damage_type
	9:   9,   // item_name
	10:  10,  // item_model
	11:  11,  // lore
	12:  12,  // rarity
	13:  13,  // enchantments
	14:  14,  // can_place_on
	15:  15,  // can_break
	16:  16,  // attribute_modifiers
	17:  17,  // custom_model_data
	18:  18,  // tooltip_display
	19:  19,  // repair_cost
	20:  20,  // creative_slot_lock
	21:  21,  // enchantment_glint_override
	22:  22,  // intangible_projectile
	23:  23,  // food
	24:  24,  // consumable
	25:  25,  // use_remainder
	26:  26,  // use_cooldown
	27:  27,  // damage_resistant
	28:  28,  // tool
	29:  29,  // weapon
	30:  30,  // attack_range
	31:  31,  // enchantable
	32:  32,  // equippable
	33:  33,  // repairable
	34:  34,  // glider
	35:  35,  // tooltip_style
	36:  36,  // death_protection
	37:  37,  // blocks_attacks
	38:  38,  // piercing_weapon
	39:  39,  // kinetic_weapon
	40:  40,  // swing_animation
	41:  41,  // additional_trade_cost
	42:  42,  // stored_enchantments
	43:  43,  // dye
	44:  44,  // dyed_color
	45:  45,  // map_color
	46:  46,  // map_id
	47:  47,  // map_decorations
	48:  48,  // map_post_processing
	49:  49,  // charged_projectiles
	50:  50,  // bundle_contents
	51:  51,  // potion_contents
	52:  52,  // potion_duration_scale
	53:  53,  // suspicious_stew_effects
	54:  54,  // writable_book_content
	55:  55,  // written_book_content
	56:  56,  // trim
	57:  57,  // debug_stick_state
	58:  58,  // entity_data
	59:  59,  // bucket_entity_data
	60:  60,  // block_entity_data
	61:  61,  // instrument
	62:  62,  // provides_trim_material
	63:  63,  // ominous_bottle_amplifier
	64:  64,  // jukebox_playable
	65:  65,  // provides_banner_patterns
	66:  66,  // recipes
	67:  67,  // lodestone_tracker
	68:  68,  // firework_explosion
	69:  69,  // fireworks
	70:  70,  // profile
	71:  71,  // note_block_sound
	72:  72,  // banner_patterns
	73:  73,  // base_color
	74:  74,  // pot_decorations
	75:  75,  // container
	76:  76,  // block_state
	77:  77,  // bees
	78:  110, // sulfur_cube_content
	79:  78,  // lock
	80:  79,  // container_loot
	81:  80,  // break_sound
	82:  81,  // villager/variant
	83:  82,  // wolf/variant
	84:  83,  // wolf/sound_variant
	85:  84,  // wolf/collar
	86:  85,  // fox/variant
	87:  86,  // salmon/size
	88:  87,  // parrot/variant
	89:  88,  // tropical_fish/pattern
	90:  89,  // tropical_fish/base_color
	91:  90,  // tropical_fish/pattern_color
	92:  91,  // mooshroom/variant
	93:  92,  // rabbit/variant
	94:  93,  // pig/variant
	95:  94,  // pig/sound_variant
	96:  95,  // cow/variant
	97:  96,  // cow/sound_variant
	98:  97,  // chicken/variant
	99:  98,  // chicken/sound_variant
	100: 99,  // zombie_nautilus/variant
	101: 100, // frog/variant
	102: 101, // horse/variant
	103: 102, // painting/variant
	104: 103, // llama/variant
	105: 104, // axolotl/variant
	106: 105, // cat/variant
	107: 106, // cat/sound_variant
	108: 107, // cat/collar
	109: 108, // sheep/color
	110: 109, // shulker/color
}

// Slot display kinds for Minecraft 26.2, mapped to canonical ids the same
// way and for the same reason: they are registry indices and they move.
var v26_2SlotDisplayIDs = map[int32]int32{
	0:  0,  // empty
	1:  1,  // any_fuel
	2:  2,  // with_any_potion
	3:  3,  // only_with_component
	4:  4,  // item
	5:  5,  // item_stack
	6:  6,  // tag
	7:  7,  // dyed
	8:  8,  // smithing_trim
	9:  9,  // with_remainder
	10: 10, // composite
}
